### ISSUE TITLE
Trying to use this WS Trade API using Postman

### ISSUE THREAD

**Issue by web-cdn** [MarkGalloway/wealthsimple-trade#7]
Thanks for sharing this awesome API guide. I am trying to use this API using postman. I was able to Authenticate by posting my credentials via POST Body and extract access token and refresh token. 

But I am not sure how to pass these as Authorization header for subsequent requests. 

I tried this and it still returned Not Authorized error. 
Authorization: { X-Access-Token  000000000000  X-Refresh-Token 00000000000 } 

Can you please share an example on how to pass on Authorization on a GET request.

**Comment by vlad-pisanov** [comment]
@web-cdn they use [bearer authentication](https://tools.ietf.org/html/rfc6750). In simple terms, you have to pass in this header:

```{ Authorization: "Bearer <your access token>"}```

for every future REST call.

Check out this implementation, it covers most of the API endpoints and how to use them:
https://github.com/ahmedsakr/wstrade-api

**Comment by web-cdn** [comment]
Thanks @vlad-pisanov  Authorization: "Bearer <your access token>" worked like a charm.
