### ISSUE TITLE
/account/activities parameters

### ISSUE THREAD

**Issue by phuzybuny** [MarkGalloway/wealthsimple-trade#9]
Does anyone have additional documentation around `/account/activities`?

Through trial-and-error, I have found that you can filter by `account-id` and `type`.

**EDIT:** After much poking and prodding, I've found `limit` and `bookmark`, where bookmark is return by each `GET` that can be used for the subsequent 'pages' in following calls.

**Comment by yusuf8ahmed** [comment]
are there any examples for type

**Comment by 8lueberry** [comment]
`buy`, `sell`, `dividend` seems to work
